#!/bin/bash

#./vscode --> run vscode 
#./vscode 7080 --> specify forwarding port
#./vscode --public --> run vscode in a public URL. 

CURPATH="$(dirname "$0")"
PORT=$(($RANDOM%1000+7000))
VSCODE_IPC_HOOK_CLI= $CURPATH/code-server*/bin/code-server --config config.yaml --user-data-dir vscode-user-dir  --extensions-dir vscode-extensions_dir  --bind-addr 127.0.0.1:$PORT >> /dev/null 2>&1 &
if [[ $1 == "--public" ]]; then
  if [ -n "$2" ]; then
    $CURPATH/host.public $PORT $2
  else
    $CURPATH/host.public $PORT
  fi
else
  if [ -n "$1" ]; then
    $CURPATH/host $PORT $1
  else
    $CURPATH/host $PORT
  fi
fi

